[[redirects]]
  from = "https://tlightchat.netlify.app:5173/*"
  to = "http://34.239.185.196:5173/:splat"
  status = 200

[[redirects]]
  from = "https://tlightchat.netlify.app:3000/*"
  to = "http://34.239.185.196:3000/:splat"
  status = 200